# Sử dụng Tomcat có sẵn Java 17
FROM tomcat:9-jdk17

# Copy file .war vào thư mục Tomcat
COPY target/*.war /usr/local/tomcat/webapps/

# Chạy Tomcat khi container khởi động
CMD ["catalina.sh", "run"]
